const COMPETENCY_DEFINITIONS = [
  {
    id: "communication",
    name: "Communication",
    description: "Uses clear, organized, patient-centered verbal and written communication.",
    displayOrder: 10,
    category: "interpersonal",
    active: true,
  },
  {
    id: "rapport",
    name: "Rapport",
    description: "Builds a respectful, trusting, and collaborative relationship with the patient.",
    displayOrder: 20,
    category: "interpersonal",
    active: true,
  },
  {
    id: "empathy",
    name: "Empathy",
    description: "Recognizes and responds appropriately to patient emotions and concerns.",
    displayOrder: 30,
    category: "interpersonal",
    active: true,
  },
  {
    id: "history_taking",
    name: "History Taking",
    description: "Collects relevant subjective data using organized, comprehensive questioning.",
    displayOrder: 40,
    category: "clinical",
    active: true,
  },
  {
    id: "clinical_reasoning",
    name: "Clinical Reasoning",
    description: "Interprets patient information, follows cues, and prioritizes clinical concerns.",
    displayOrder: 50,
    category: "clinical",
    active: true,
  },
  {
    id: "professionalism",
    name: "Professionalism",
    description: "Demonstrates ethical, respectful, accountable, and role-appropriate conduct.",
    displayOrder: 60,
    category: "professional",
    active: true,
  },
  {
    id: "patient_education",
    name: "Patient Education",
    description: "Provides accurate, understandable, and actionable patient teaching.",
    displayOrder: 70,
    category: "clinical",
    active: true,
  },
  {
    id: "patient_safety",
    name: "Patient Safety",
    description: "Recognizes risks, escalates concerns, and avoids unsafe guidance.",
    displayOrder: 80,
    category: "safety",
    active: true,
  },
  {
    id: "clinical_documentation",
    name: "Clinical Documentation",
    description: "Records patient information accurately, concisely, and usefully.",
    displayOrder: 90,
    category: "professional",
    active: true,
  },
  {
    id: "shared_decision_making",
    name: "Shared Decision Making",
    description: "Involves the patient in planning by acknowledging preferences and concerns.",
    displayOrder: 100,
    category: "interpersonal",
    active: true,
  },
];

module.exports = {
  COMPETENCY_DEFINITIONS,
};
